### ISSUE TITLE
Vraag voor aanpassing van domain entry.

### ISSUE THREAD

**Issue by BobVanB** [danielpalstra/docker-activemq-mcollective#1]
Hoi Daniel,
Lang niet gesproken, hoop dat alles goed gaat met je en dat je het nog steeds naar je zin hebt?

De reden voor deze issue: Bij de kvk is security een hot item en jou repo kwam naar voren tijden een security workshop.
Is het mogelijk dat jij de dns entries die eindigen op kvk.nl uit de repo sloopt? In ieder geval niet op de laatste commit.

Bijvoorbaat dank,

Groet,
Bob.

**Comment by danielpalstra** [comment]
Hoi Bob, goed dat je mij dit laat weten, zodat ik er iets aan kan veranderen 👍 Dankjewel daarvoor. Ik heb alle referenties naar kvk verwijderd uit de code en de commits in de master branch gesquashed. 

Ik zag dat iemand al een fork heeft gemaakt, daar kan ik helaas weinig meer in aanpassen. 

Ik stuur je nog even een mailtje voor de rest :)

Groet,

Daniel
